name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["https://github.com/users/jussetain/projects/6"]
assignees:
  - jussetain
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email address, discord id, instagram handle, etc.
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A concise description of what you're experiencing, a concise description of what you expected to happen and steps to reproduce"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What operating system are you seeing the problem on?
      placeholder: ex. windows 11, macOS Sierra, Debian 11
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: Browser
      description: What browser are you seeing the problem on?
      placeholder: ex. chrome 132.0.6834.160, etc
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
